##### Week 18 In Class Notes
###### January 26, 2022

How do you evaluate the performance of your model when you're trying to predict a continuous variable? Why?

Mean Squared Error
Root Mean Squared Error
Mean Absolute Error

These metrics measure the error between the actual target value and the predicted target value, MSE and RMSE punish larger errors more than MAE does; both RMSE and MAE have units that are equal to the model units.

In [13]:
import numpy as np

some_array = np.array([1,2,3,4,5,6])
print(some_array)

#multiply each value by 3 as simply as possible
array_x3 = array*3
print(array_x3)

[1 2 3 4 5 6]
[ 3  6  9 12 15 18]


#### Class Notes

###### Neural Networks 
- process that mimics human brain to understand patterns in stat
- each node is a 'preceptron' which is similar to multiple linear regression
- the result of the preceptron feeds an activation function (converts node input to output)
    - rectified linear activation unit
- hidden layers fine tine the results intil the error is minimized
- deep learning algorithm - a neural network with more than three layers


Improving neural 
- forward propagation (input to output)
    - dot product
    - higher weights for better performance
backward propagation

Thought exercise - steps your brain takes when a deer jumps in front of your car
- eyes take in the movement
- panic response
- hit breaks 
- check rear view mirror and oncoming traffic
- swerve

very similar to the way a neural network processes an event

###### ReLU and Activation Functions
- activation functions allow our algorithm to learn more complex patterns in data
- simplest non-linear is ReLU:
        0 if input >0:
            return input
        else
            return 0
- can use more complicated activation functions like tanh, but ReLU is sufficient and very performant for a wide variety of problems

###### Forward and Backward Propagation
- forward - takes ubput values and propagates forward through the hidden layers to oputput; used to calculate predictions and errors
- backward - goes back one layer at a time from output to input to see how small changes impact the difference between the predicted and actual values; working to minimize the loss function

Advances in Neural networks come from advances in hardware: memory usage, multi-threading, etc.
advances in mathematic efficiency: compreshion algorithms

Article to read: pytourch (similar to keris and tensorflow)
https://neptune.ai/blog/pytorch-loss-functions

"Loss functions are used to gauge the error between the prediction output and the provided target value. A loss function tells us how far the algorithm model is from realizing the expected outcome. The word ‘loss’ means the penalty that the model gets for failing to yield the desired results."

Mean Absolute Error Loss
Mean Squared Error Loss
Negative Log-Likelihood Loss
Cross-Entropy Loss
Hinge Embedding Loss
Margin Ranking Loss
Triplet Margin Loss
Kullback-Leibler divergence

examples of each and when to use in the article

###### How do neural networks learn and grow

- usually used for supervised learning so there is an answer they can tune to
- back propagation is critical to the learning process

In [3]:
import pandas as pd

In [5]:
diabetes_df = pd.read_csv("../Datasets/diabetes.csv")
diabetes_df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [13]:
X = diabetes_df.drop('Outcome', axis=1).values
y = diabetes_df['Outcome'].values

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42, stratify=y)

sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)
print(X_train)
print(y_train)

[[ 0.93138344  2.0179454   0.78066953 ...  0.43148259 -0.37477883
   0.63212912]
 [ 0.63260632 -1.14861888  0.46538785 ... -0.1198324  -0.29416766
   0.71699246]
 [-0.56250219 -0.47692343 -0.2702694  ... -0.20958135  2.74517192
   0.03808578]
 ...
 [-0.86127931 -0.76479291  0.04501228 ...  0.76483585 -0.78380586
  -0.30136756]
 [ 0.63260632  2.20985838  1.2010451  ...  0.43148259 -0.60466993
   2.75371249]
 [ 0.03505207  0.73852549 -0.58555107 ... -0.33779414 -0.57779954
   0.29267578]]
[1 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 1 1
 1 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0
 0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 1 1 1
 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 1
 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0
 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 0 1 1 1

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F #where the activation function are

In [15]:
#create tensors = matrices

#same values, but slightly different format to make it easier for torch
X_train = torch.FloatTensor(X_train) 
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train) 
y_test = torch.LongTensor(y_test)

print(X_train)

tensor([[ 0.9314,  2.0179,  0.7807,  ...,  0.4315, -0.3748,  0.6321],
        [ 0.6326, -1.1486,  0.4654,  ..., -0.1198, -0.2942,  0.7170],
        [-0.5625, -0.4769, -0.2703,  ..., -0.2096,  2.7452,  0.0381],
        ...,
        [-0.8613, -0.7648,  0.0450,  ...,  0.7648, -0.7838, -0.3014],
        [ 0.6326,  2.2099,  1.2010,  ...,  0.4315, -0.6047,  2.7537],
        [ 0.0351,  0.7385, -0.5856,  ..., -0.3378, -0.5778,  0.2927]])


In [25]:
#aritficial neural network
#creating a class using the neural network module
class ANN_Model(nn.Module):
    
    #uses the parameters for nn.Module, check documentation
    def __init__(self, input_features=8, hidden1=20, hidden2=20, out_features=2):
        
        # keyword super is a computed indirect reference, 
        # iolates changes and makes sure children in the layers of multiple inheritance
        # are calling the correct parents
        super().__init__() 
        
        self.layer_1_connection = nn.Linear(input_features, hidden1)
        self.layer_2_connection = nn.Linear(hidden1, hidden2)
        self.out = nn.Linear(hidden2, out_features)
        
    def forward(self, x):
        #apply activation functions
        x = F.relu(self.layer_1_connection(x))
        x = F.relu(self.layer_2_connection(x))
        x = self.out(x)
        return x

In [26]:
torch.manual_seed(42)

#create instance of model
ann = ANN_Model()

In [27]:
#loss function
loss_function = nn.CrossEntropyLoss()

#optimizer
optimizer = torch.optim.Adam(ann.parameters(), lr=0.01)

In [28]:
#run model through multiple epochs/iterations
final_loss = []
n_epochs = 500
for epoch in range(n_epochs):
    y_pred = ann.forward(X_train)
    loss = loss_function(y_pred, y_train)
    final_loss.append(loss)
    
    if epoch % 10 == 1:
        print(f'Epoch number:{epoch} with loss: {loss}')
    
    # impliment optimizer
    # gradient descent - zero the gradient before running backwards propagation
    optimizer.zero_grad()
    loss.backward()
    #perform optimization step for each epoch
    optimizer.step()

Epoch number:1 with loss: 0.6474701762199402
Epoch number:11 with loss: 0.5270779132843018
Epoch number:21 with loss: 0.4539138376712799
Epoch number:31 with loss: 0.4234800934791565
Epoch number:41 with loss: 0.39819812774658203
Epoch number:51 with loss: 0.3721073567867279
Epoch number:61 with loss: 0.3437724709510803
Epoch number:71 with loss: 0.31378453969955444
Epoch number:81 with loss: 0.28582650423049927
Epoch number:91 with loss: 0.25994446873664856
Epoch number:101 with loss: 0.2377135008573532
Epoch number:111 with loss: 0.21422426402568817
Epoch number:121 with loss: 0.19071196019649506
Epoch number:131 with loss: 0.17592839896678925
Epoch number:141 with loss: 0.15840257704257965
Epoch number:151 with loss: 0.14416620135307312
Epoch number:161 with loss: 0.12847743928432465
Epoch number:171 with loss: 0.11491046100854874
Epoch number:181 with loss: 0.10371395200490952
Epoch number:191 with loss: 0.09079709649085999
Epoch number:201 with loss: 0.07853538542985916
Epoch numb

In [29]:
#predictions 
y_pred = []

with torch.no_grad():
    for i, data in enumerate(X_test):
        prediction = ann(data)
        y_pred.append(prediction.argmax())

In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.81      0.78       150
           1       0.59      0.49      0.54        81

    accuracy                           0.70       231
   macro avg       0.67      0.65      0.66       231
weighted avg       0.69      0.70      0.69       231

